on: [push]

name: Build Rust project

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend

      - name: Build
        run: cargo build
